version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    volumes:
      - ./app:/app
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - HOST=${DJANGO_HOST}
      - PORT=${DJANGO_PORT}
      - POST_TIMEOUT=${POST_TIMEOUT}
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    container_name: ${DB_HOST}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
