# Generated by Django 4.0.5 on 2022-06-12 18:14

from django.db import migrations, models
import django.utils.timezone
import note.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('address', models.CharField(default=note.utils.random_address_generator, max_length=32, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
